
system_packages:
  - git
  - vim
  - zsh
  - lsd

flat_paks:
  - com.github.tchx84.Flatseal
  - org.nickvision.tubeconverter
  - org.mozilla.Thunderbird
  - com.github.taiko2k.tauonmb
  - md.obsidian.Obsidian
  - com.nextcloud.desktopclient.nextcloud
  - com.mattjakeman.ExtensionManager
  - com.discordapp.Discord
  - ca.desrt.dconf-editor
  - com.bitwarden.desktop
