---
- hosts: localhost
  connection: local

  vars_files:
    - config.yml

  tasks:
  #  - import_tasks: tasks/install_packages.yml
#    - import_tasks: tasks/add_dotfiles.yml
#    - import_tasks: tasks/conf_zsh.yml
    - import_tasks: tasks/conf_gnome_for_loop.yml
