---
- debug:
    msg: Start Gnome DE configuration

- name: Set weather location to Turku
  community.general.dconf:
    key: /org/gnome/Weather/locations
    value: "[<(uint32 2, <('Turku', 'EFTU', false, [(1.0562150914829993, 0.38862665259516821)], @a(dd) [])>)>]"

- name: Set GWeather4 to use centigrade
  community.general.dconf:
    key: /org/gnome/GWeather4/temperature
    value: "'centigrade'"

- name: Set dark theme as prefered theme
  community.general.dconf:
    key: /org/gnome/desktop/interface/color-scheme
    value: "'prefer-dark'"

- name: Set gtk theme to Adwaita-dark
  community.general.dconf:
    key: /org/gnome/desktop/interface/gtk-theme
    value: "'Adwaita-dark'"


- name: Set mouse accel-profile to flat
  community.general.dconf:
    key: /org/gnome/desktop/peripherals/mouse/accel-profile
    value: "'flat'"

- name: Set mouse speed
  community.general.dconf:
    key: /org/gnome/desktop/peripherals/mouse/speed
    value: "0.061946902654867353"

- name: Set keybindings
  community.general.dconf:
    key: /org/gnome/desktop/wm/keybindings/close
    value: "['<Super>x']"

- name: Set keybindings
  community.general.dconf:
    key: /org/gnome/desktop/wm/keybindings/move-to-workspace-1
    value: "['<Shift><Super>1']"

- name: Set keybindings
  community.general.dconf:
    key: /org/gnome/desktop/wm/keybindings/close/move-to-workspace-2
    value: "['<Shift><Super>2']"

- name: Set keybindings
  community.general.dconf:
    key: /org/gnome/desktop/wm/keybindings/close/move-to-workspace-3
    value: "['<Shift><Super>3']"

- name: Set keybindings
  community.general.dconf:
    key: /org/gnome/desktop/wm/keybindings/close/move-to-workspace-4
    value: "['<Shift><Super>4']"

- name: Set keybindings
  community.general.dconf:
    key: /org/gnome/desktop/wm/keybindings/close/switch-to-workspace-1
    value: "['<Super>1']"

- name: Set keybindings
  community.general.dconf:
    key: /org/gnome/desktop/wm/keybindings/close/switch-to-workspace-2
    value: "['<Super>2']"

- name: Set keybindings
  community.general.dconf:
    key: /org/gnome/desktop/wm/keybindings/close/switch-to-workspace-3
    value: "['<Super>3']"

- name: Set keybindings
  community.general.dconf:
    key: /org/gnome/desktop/wm/keybindings/close/switch-to-workspace-4
    value: "['<Super>4']"

- name: Set keybindings
  community.general.dconf:
    key: /org/gnome/desktop/wm/keybindings/close/switch-to-workspace-left
    value: "['<Control><Super>Left']"

- name: Set keybindings
  community.general.dconf:
    key: /org/gnome/desktop/wm/keybindings/close/switch-to-workspace-right
    value: "['<Control><Super>Right']"

- name: Set keybindings
  community.general.dconf:
    key: /org/gnome/desktop/wm/preferences/resize-with-right-button
    value: "true"
