---
- name: Install gnome shell extensions
  become: true
  package:
    name: "{{ item }}"
    state: present
  loop:
    - "{{ gnome-shell-extensions }}"
  loop_control:
    label: "Installed {{ item }}"

- name: Set gnome config keys and values
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
  with_dict:
    - "{{ gnome_confs }}"
  loop_control:
    label: "Set {{ item.key }} to {{ item.value }}"
